---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04 # OS that is gonna run the job
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.TANUJ}}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        uses: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        uses: docker-compose run --rm app sh -c "flake8"

        